stages:
  - lint
  - security
  - test

lint:
  stage: lint
  image: python:3.11
  script:
    - echo "Lint stage"

security:
  stage: security
  image: python:3.11
  script:
    - echo "Security stage"

tests:
  stage: test
  image: python:3.11
  script:
    - echo "Test stage"